Make the YAML resilient to port-forward failures

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -144,22 +144,28 @@ jobs:
             kubectl -n stackrox get pod
             POD="$(kubectl -n stackrox get pod -o jsonpath='{.items[?(@.metadata.labels.app=="scanner")].metadata.name}')"
             [[ -n "${POD}" ]]
-            echo "${POD}"
             kubectl -n stackrox wait --for=condition=ready "pod/${POD}" --timeout=3m
             kubectl -n stackrox get pod
-            nohup kubectl port-forward -n stackrox "${POD}" "8080:8080" & # Legacy clairify endpoint
-            nohup kubectl port-forward -n stackrox "${POD}" "8081:8081" & # gRPC endpoint
-            # It looks like we need this sleep, otherwise the port forward never starts.
-            sleep 5
 
-      - run:
-          name: Wait for API to be available
-          command: |
-            curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8080/clairify/ping'
-            cat nohup.out || true
+            success=0
+            for i in $(seq 1 10); do
+              rm FAIL || true
+              nohup kubectl port-forward -n stackrox "${POD}" "8080:8080" & # Legacy clairify endpoint
+              nohup kubectl port-forward -n stackrox "${POD}" "8081:8081" & # gRPC endpoint
+              curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8080/clairify/ping' || touch FAIL
+              curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8081/v1/ping' || touch FAIL
+              if [[ ! -f FAIL ]]; then
+                success=1
+                break
+              fi
+              echo "Port-forwarding failed."
+              cat nohup.out || true
+              rm nohup.out || true
+              killall kubectl
+              sleep 5
+            done
 
-            curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8081/v1/ping'
-            cat nohup.out || true
+            [[ "${success}" -gt 0 ]]
 
       - run:
           name: Run sanity tests
