Fix?

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,6 +18,37 @@ runOnAllTags: &runOnAllTags
     tags:
       only: /.*/
 
+waitForScannerPodAndPF: &waitForScannerPodAndPF
+  run:
+    name: Wait for the pod to be running, and port-forward
+    command: |
+      sleep 5
+      kubectl -n stackrox get pod
+      POD="$(kubectl -n stackrox get pod -o jsonpath='{.items[?(@.metadata.labels.app=="scanner")].metadata.name}')"
+      [[ -n "${POD}" ]]
+      kubectl -n stackrox wait --for=condition=ready "pod/${POD}" --timeout=3m
+      kubectl -n stackrox get pod
+
+      success=0
+      for i in $(seq 1 10); do
+        nohup kubectl port-forward -n stackrox "${POD}" "8080:8080" & # Legacy clairify endpoint
+        nohup kubectl port-forward -n stackrox "${POD}" "8443:8443" & # gRPC endpoint
+        curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8080/clairify/ping' || touch FAIL
+        curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8443/v1/ping' || touch FAIL
+        if [[ ! -f FAIL ]]; then
+          success=1
+          break
+        fi
+        echo "Port-forwarding failed."
+        cat nohup.out || true
+        rm nohup.out || true
+        rm FAIL || true
+        pkill kubectl || true
+        sleep 5
+      done
+
+      [[ "${success}" -gt 0 ]]
+
 runOnAllTagsWithDockerIOPullCtx: &runOnAllTagsWithDockerIOPullCtx
   <<: *runOnAllTags
   context: docker-io-pull
@@ -245,40 +276,11 @@ commands:
               make deploy
             fi
 
-      - run:
-          name: Wait for the pod to be running, and port-forward
-          command: |
-            sleep 5
-            kubectl -n stackrox get pod
-            POD="$(kubectl -n stackrox get pod -o jsonpath='{.items[?(@.metadata.labels.app=="scanner")].metadata.name}')"
-            [[ -n "${POD}" ]]
-            kubectl -n stackrox wait --for=condition=ready "pod/${POD}" --timeout=3m
-            kubectl -n stackrox get pod
-
-            success=0
-            for i in $(seq 1 10); do
-              nohup kubectl port-forward -n stackrox "${POD}" "8080:8080" & # Legacy clairify endpoint
-              nohup kubectl port-forward -n stackrox "${POD}" "8443:8443" & # gRPC endpoint
-              curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8080/clairify/ping' || touch FAIL
-              curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8443/v1/ping' || touch FAIL
-              if [[ ! -f FAIL ]]; then
-                success=1
-                break
-              fi
-              echo "Port-forwarding failed."
-              cat nohup.out || true
-              rm nohup.out || true
-              rm FAIL || true
-              pkill kubectl || true
-              sleep 5
-            done
-
-            [[ "${success}" -gt 0 ]]
+      - *waitForScannerPodAndPF
 
       - run:
           name: Run sanity tests
           command: |
-            export SCANNER_ENDPOINT=https://localhost:8080
             make e2e-tests
 
       - run:
@@ -287,6 +289,39 @@ commands:
             .circleci/collect-service-logs.sh stackrox
             .circleci/collect-service-logs.sh kube-system
           when: always
+
+      - run:
+          name: Verify the scanner did not restart
+          command: |
+            if [[ "$(ls /tmp/k8s-service-logs/stackrox/*-previous.log | wc -l)" != 0 ]]; then
+                ls /tmp/k8s-service-logs/stackrox/*-previous.log
+                exit 1
+            fi
+            cat nohup.out || true
+          when: always
+
+      - run:
+          name: Delete license and bounce pod
+          command: |
+            kubectl -n stackrox delete secret scanner-license
+            POD="$(kubectl -n stackrox get pod -o jsonpath='{.items[?(@.metadata.labels.app=="scanner")].metadata.name}')"
+            [[ -n "${POD}" ]]
+            kubectl -n stackrox delete pod "${POD}"
+
+      - *waitForScannerPodAndPF
+
+      - run:
+          name: Run no license tests
+          command: |
+            make no-license-tests
+
+      - run:
+          name: Collect k8s logs
+          command: |
+            .circleci/collect-service-logs.sh stackrox
+            .circleci/collect-service-logs.sh kube-system
+          when: always
+
 
       - store_artifacts:
           path: /tmp/k8s-service-logs
