Fix tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,37 +18,6 @@ runOnAllTags: &runOnAllTags
     tags:
       only: /.*/
 
-waitForScannerPodAndPF: &waitForScannerPodAndPF
-  run:
-    name: Wait for the pod to be running, and port-forward
-    command: |
-      sleep 5
-      kubectl -n stackrox get pod
-      POD="$(kubectl -n stackrox get pod -o jsonpath='{.items[?(@.metadata.labels.app=="scanner")].metadata.name}')"
-      [[ -n "${POD}" ]]
-      kubectl -n stackrox wait --for=condition=ready "pod/${POD}" --timeout=3m
-      kubectl -n stackrox get pod
-
-      success=0
-      for i in $(seq 1 10); do
-        nohup kubectl port-forward -n stackrox "${POD}" "8080:8080" & # Legacy clairify endpoint
-        nohup kubectl port-forward -n stackrox "${POD}" "8443:8443" & # gRPC endpoint
-        curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8080/clairify/ping' || touch FAIL
-        curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8443/v1/ping' || touch FAIL
-        if [[ ! -f FAIL ]]; then
-          success=1
-          break
-        fi
-        echo "Port-forwarding failed."
-        cat nohup.out || true
-        rm nohup.out || true
-        rm FAIL || true
-        pkill kubectl || true
-        sleep 5
-      done
-
-      [[ "${success}" -gt 0 ]]
-
 runOnAllTagsWithDockerIOPullCtx: &runOnAllTagsWithDockerIOPullCtx
   <<: *runOnAllTags
   context: docker-io-pull
@@ -73,6 +42,46 @@ commands:
                 circleci step halt
               fi
             fi
+
+  wait-for-scanner-and-pf:
+    description: Wait for the scanner pod to meet the given condition, and port-forward
+    parameters:
+      condition:
+        type: string
+      sleep-after-condition-met:
+        type: integer
+        default: 0
+    steps:
+      - run:
+          name: Wait for the pod to be << parameters.condition >>, and port-forward
+          command: |
+            sleep 5
+            kubectl -n stackrox get pod
+            POD="$(kubectl -n stackrox get pod -o jsonpath='{.items[?(@.metadata.labels.app=="scanner")].metadata.name}')"
+            [[ -n "${POD}" ]]
+            kubectl -n stackrox wait "--for=condition=<< parameters.condition >>" "pod/${POD}" --timeout=3m
+            sleep << parameters.sleep-after-condition-met >>
+            kubectl -n stackrox get pod
+
+            success=0
+            for i in $(seq 1 10); do
+              nohup kubectl port-forward -n stackrox "${POD}" "8080:8080" & # Legacy clairify endpoint
+              nohup kubectl port-forward -n stackrox "${POD}" "8443:8443" & # gRPC endpoint
+              curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8080/clairify/ping' || touch FAIL
+              curl --retry 12 --retry-connrefused -4 --retry-delay 5 --retry-max-time 60 -skf 'https://localhost:8443/v1/ping' || touch FAIL
+              if [[ ! -f FAIL ]]; then
+                success=1
+                break
+              fi
+              echo "Port-forwarding failed."
+              cat nohup.out || true
+              rm nohup.out || true
+              rm FAIL || true
+              pkill kubectl || true
+              sleep 5
+            done
+
+            [[ "${success}" -gt 0 ]]
 
   setup-gcp:
     description: Set up GCP service account and configure gcloud
@@ -276,7 +285,8 @@ commands:
               make deploy
             fi
 
-      - *waitForScannerPodAndPF
+      - wait-for-scanner-and-pf:
+          condition: Ready
 
       - run:
           name: Run sanity tests
@@ -308,7 +318,9 @@ commands:
             [[ -n "${POD}" ]]
             kubectl -n stackrox delete pod "${POD}"
 
-      - *waitForScannerPodAndPF
+      - wait-for-scanner-and-pf:
+          condition: Initialized
+          sleep-after-condition-met: 60
 
       - run:
           name: Run no license tests
