Try to fail the fetch-vuln-feed-data step if a download fails

diff --git a/.tekton/scanner-pull-request.yaml b/.tekton/scanner-pull-request.yaml
--- a/.tekton/scanner-pull-request.yaml
+++ b/.tekton/scanner-pull-request.yaml
@@ -229,9 +229,14 @@ spec:
               )
               for blob in "${blobs[@]}"; do
                 echo "https://storage.googleapis.com/definitions.stackrox.io/scanner-data/latest/${blob} > $(workspaces.source.path)/source/blob-${blob}"
-                curl --fail --show-error --retry 4 --retry-max-time 30 --retry-connrefused \
+                curl --fail -s --show-error --retry 4 --retry-max-time 30 --retry-connrefused \
                   --output "$(workspaces.source.path)/source/blob-${blob}" \
                   "https://storage.googleapis.com/definitions.stackrox.io/scanner-data/latest/${blob}"
+
+                if [ "$?" != "0" ]; then
+                    echo "Failed to download"
+                    exit 1
+                fi
               done
       workspaces:
       - name: source
